windowrule {
    name = suppress-maximize-events
    match:class = .*
    suppress_event = maximize
}

windowrule {
    name = float-settings
    match:class = ^(pavucontrol|nm-connection-editor|blueman-manager|org.gnome.Settings)$
    float = true
    center = true
    size = 850 600
}

windowrule {
    name = float-file-dialogs
    match:title = ^(Open|Save File|Save As|Choose Files|Open File)$
    float = true
    center = true
    size = 900 650
}

windowrule {
    name = idle-inhibit-media
    match:class = ^(firefox|chromium|Google-chrome|mpv|vlc)$
    match:fullscreen = true
    idle_inhibit = fullscreen
}
